name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    name: deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: |
          yarn install
          yarn test:unit
          yarn build


